/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BrandProfile {
  'campaignRequirements' : string,
  'description' : string,
  'companyName' : string,
  'budget' : bigint,
}
export interface CollaborationRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'rejected' : null } |
    { 'accepted' : null },
  'createdAt' : Time,
  'sender' : Principal,
  'message' : string,
  'receiver' : Principal,
}
export interface ContactFormSubmission {
  'id' : bigint,
  'name' : string,
  'submittedAt' : Time,
  'email' : string,
  'message' : string,
}
export type ExternalBlob = Uint8Array;
export interface InfluencerProfile {
  'bio' : string,
  'categories' : Array<string>,
  'name' : string,
  'socialMedia' : Array<SocialMediaMetrics>,
  'rates' : bigint,
}
export interface PortfolioItem {
  'id' : bigint,
  'title' : string,
  'createdAt' : Time,
  'description' : string,
  'image' : ExternalBlob,
  'influencerId' : Principal,
}
export interface SocialMediaMetrics {
  'engagementRate' : number,
  'platform' : string,
  'followers' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'id' : Principal,
  'userType' : UserType,
  'brandProfile' : [] | [BrandProfile],
  'createdAt' : Time,
  'influencerProfile' : [] | [InfluencerProfile],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserType = { 'influencer' : null } |
  { 'brand' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPortfolioItem' : ActorMethod<[string, string, ExternalBlob], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createUserProfile' : ActorMethod<
    [UserType, [] | [InfluencerProfile], [] | [BrandProfile]],
    undefined
  >,
  'deleteCollaborationRequest' : ActorMethod<[bigint], undefined>,
  'deletePortfolioItem' : ActorMethod<[bigint], undefined>,
  'deleteUserProfile' : ActorMethod<[Principal], undefined>,
  'getAllBrands' : ActorMethod<[], Array<UserProfile>>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactFormSubmission>>,
  'getAllInfluencers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPortfolioItems' : ActorMethod<[Principal], Array<PortfolioItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRequests' : ActorMethod<[Principal], Array<CollaborationRequest>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<
    [UserType, [] | [InfluencerProfile], [] | [BrandProfile]],
    undefined
  >,
  'sendCollaborationRequest' : ActorMethod<[Principal, string], bigint>,
  'submitContactForm' : ActorMethod<[string, string, string], bigint>,
  'updateRequestStatus' : ActorMethod<
    [bigint, { 'rejected' : null } | { 'accepted' : null }],
    undefined
  >,
  'updateUserProfile' : ActorMethod<
    [[] | [InfluencerProfile], [] | [BrandProfile]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];