/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserType = IDL.Variant({
  'influencer' : IDL.Null,
  'brand' : IDL.Null,
});
export const SocialMediaMetrics = IDL.Record({
  'engagementRate' : IDL.Float64,
  'platform' : IDL.Text,
  'followers' : IDL.Nat,
});
export const InfluencerProfile = IDL.Record({
  'bio' : IDL.Text,
  'categories' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'socialMedia' : IDL.Vec(SocialMediaMetrics),
  'rates' : IDL.Nat,
});
export const BrandProfile = IDL.Record({
  'campaignRequirements' : IDL.Text,
  'description' : IDL.Text,
  'companyName' : IDL.Text,
  'budget' : IDL.Nat,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'userType' : UserType,
  'brandProfile' : IDL.Opt(BrandProfile),
  'createdAt' : Time,
  'influencerProfile' : IDL.Opt(InfluencerProfile),
});
export const ContactFormSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const PortfolioItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'image' : ExternalBlob,
  'influencerId' : IDL.Principal,
});
export const CollaborationRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  }),
  'createdAt' : Time,
  'sender' : IDL.Principal,
  'message' : IDL.Text,
  'receiver' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPortfolioItem' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUserProfile' : IDL.Func(
      [UserType, IDL.Opt(InfluencerProfile), IDL.Opt(BrandProfile)],
      [],
      [],
    ),
  'deleteCollaborationRequest' : IDL.Func([IDL.Nat], [], []),
  'deletePortfolioItem' : IDL.Func([IDL.Nat], [], []),
  'deleteUserProfile' : IDL.Func([IDL.Principal], [], []),
  'getAllBrands' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getAllInfluencers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPortfolioItems' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PortfolioItem)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRequests' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CollaborationRequest)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func(
      [UserType, IDL.Opt(InfluencerProfile), IDL.Opt(BrandProfile)],
      [],
      [],
    ),
  'sendCollaborationRequest' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'updateRequestStatus' : IDL.Func(
      [IDL.Nat, IDL.Variant({ 'rejected' : IDL.Null, 'accepted' : IDL.Null })],
      [],
      [],
    ),
  'updateUserProfile' : IDL.Func(
      [IDL.Opt(InfluencerProfile), IDL.Opt(BrandProfile)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserType = IDL.Variant({ 'influencer' : IDL.Null, 'brand' : IDL.Null });
  const SocialMediaMetrics = IDL.Record({
    'engagementRate' : IDL.Float64,
    'platform' : IDL.Text,
    'followers' : IDL.Nat,
  });
  const InfluencerProfile = IDL.Record({
    'bio' : IDL.Text,
    'categories' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'socialMedia' : IDL.Vec(SocialMediaMetrics),
    'rates' : IDL.Nat,
  });
  const BrandProfile = IDL.Record({
    'campaignRequirements' : IDL.Text,
    'description' : IDL.Text,
    'companyName' : IDL.Text,
    'budget' : IDL.Nat,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'userType' : UserType,
    'brandProfile' : IDL.Opt(BrandProfile),
    'createdAt' : Time,
    'influencerProfile' : IDL.Opt(InfluencerProfile),
  });
  const ContactFormSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const PortfolioItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'image' : ExternalBlob,
    'influencerId' : IDL.Principal,
  });
  const CollaborationRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'rejected' : IDL.Null,
      'accepted' : IDL.Null,
    }),
    'createdAt' : Time,
    'sender' : IDL.Principal,
    'message' : IDL.Text,
    'receiver' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPortfolioItem' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUserProfile' : IDL.Func(
        [UserType, IDL.Opt(InfluencerProfile), IDL.Opt(BrandProfile)],
        [],
        [],
      ),
    'deleteCollaborationRequest' : IDL.Func([IDL.Nat], [], []),
    'deletePortfolioItem' : IDL.Func([IDL.Nat], [], []),
    'deleteUserProfile' : IDL.Func([IDL.Principal], [], []),
    'getAllBrands' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getAllInfluencers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPortfolioItems' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PortfolioItem)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRequests' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CollaborationRequest)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func(
        [UserType, IDL.Opt(InfluencerProfile), IDL.Opt(BrandProfile)],
        [],
        [],
      ),
    'sendCollaborationRequest' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateRequestStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({ 'rejected' : IDL.Null, 'accepted' : IDL.Null }),
        ],
        [],
        [],
      ),
    'updateUserProfile' : IDL.Func(
        [IDL.Opt(InfluencerProfile), IDL.Opt(BrandProfile)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };